Feature/frontend
Mat24/weather_service pull request #1
Opened 2018-01-17 15:32 UTC by Mat24

2018-01-17 22:42 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service.ex
> +      err -> err
The `else` statement could be removed here, at least you want to personalize the response error

2018-01-17 23:00 UTC, ever-cifuentes-globant requested changes

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/utils.ex
> +      err -> err
Same here, the `else` could be omitted.

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/utils.ex
> +    hours = date_time.hour
`hours` and `minutes` could be removed and put them directly in the interpolation.

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/weather.ex
> +    "with: #{inspect params}")
align the string with the start of the string of the previous line, "Task..."

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/weather.ex
> +      err -> IO.inspect err
the return error could be replaced to `{:error, :internal_server_error}`

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/weather.ex
> +        {:error, error}
The return error tuple must be in the same line of the pattern matching when it's enough short.

```elixir
error -> {:error, error}
```

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/weather_element.ex
> +defmodule WeatherElement do
Check this module, I guess the most of this code is obsolete right now.

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service/lib/weather_service/weather_request.ex
> +      err -> err
Same here with the `else`

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service_web/spec/controllers/weather_controller_spec.exs
> +        |> IO.inspect()
Do not forget to remove the `IO.inspect` printings

2018-01-17 23:00 UTC, ever-cifuentes-globant commented on apps/weather_service_web/spec/support/factory.ex
> +      wind: "",
Complete the missing factory weather fields

2018-01-18 14:20 UTC, ever-cifuentes-globant approved these changes

2018-01-18 19:13 UTC, ricardo-mender-globant commented
Lgtm, nice work!

2018-01-19 23:29 UTC, merged